user:
  outputs:
    default:
      account: XDIPUGC-GN94204
      auth_type: password
      client_session_keep_alive: false
      connect_retries: 3
      connect_timeout: 30
      database: ANALYTICS
      password: GRM11@30ptmttm
      retry_on_database_errors: true
      role: ACCOUNTADMIN
      schema: dbt_ngiamblanco
      threads: 6
      type: snowflake
      user: NICOL
      warehouse: TRANSFORM
  target: default
